# Generated by Django 3.2.9 on 2021-12-18 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.TextField()),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('price', models.CharField(max_length=200)),
                ('photo', models.ImageField(upload_to=None)),
            ],
        ),
    ]
